"""Initial Migration

Revision ID: 7f64b8697706
Revises: 587a8fec2735
Create Date: 2022-02-13 14:19:23.358417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f64b8697706'
down_revision = '587a8fec2735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('quote', sa.String(length=255), nullable=True),
    sa.Column('permalink', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random')
    # ### end Alembic commands ###
