"""Initial Migration

Revision ID: f7abe9e99725
Revises: 7f64b8697706
Create Date: 2022-02-13 14:25:46.354071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7abe9e99725'
down_revision = '7f64b8697706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('random', 'permalink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random', sa.Column('permalink', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
